### ISSUE TITLE
Integrate MongoDB

### ISSUE THREAD

**Issue by crossoverJie** [cprobe/cprobe#11]
Integrate https://github.com/percona/mongodb_exporter

**Comment by UlricQin** [comment]
最近清闲了一些，我也看看 MongoDB，看起来 MongoDB 还挺多内容的：https://www.datadoghq.com/blog/collecting-mongodb-metrics-and-statistics/

**Comment by UlricQin** [comment]
[http://t.csdnimg.cn/I3xcT](http://t.csdnimg.cn/I3xcT) 这个文章很长，很全，把 MongoDB 的相关概念都做了介绍，要能玩明白监控数据采集，是需要对基础概念和架构有了解的

**Comment by UlricQin** [comment]
嵌入进来了，不过不太熟，相关的仪表盘和告警规则均未整理

**Comment by UlricQin** [comment]
仪表盘和告警规则都整理完了
