### ISSUE TITLE
集成es exporter

### ISSUE THREAD

**Issue by joker-bai** [cprobe/cprobe#15]
集成es：https://github.com/prometheus-community/elasticsearch_exporter

**Comment by UlricQin** [comment]
es 采集的数据得好好梳理一下，es 默认采集的指标太多了，有些 segment 级别的指标、http 细粒度的 request 指标个人感觉意义不大，容易把监控系统打死

**Comment by joker-bai** [comment]
# ES监控指标

##集群运行的重要指标：

- Status：状态群集的状态。红色：部分主分片未分配。黄色：部分副本分片未分配。绿色：所有分片分配ok。
- Nodes：节点。包括群集中的节点总数，并包括成功和失败节点的计数。 Count of Active
- Shards：活动分片计数。集群中活动分片的数量。 Relocating Shards：重定位分片。由于节点丢失而移动的分片计数。
- Initializing Shards：初始化分片。由于添加索引而初始化的分片计数。 Unassigned
- Shards。未分配的分片。尚未创建或分配副本的分片计数。

## 请求检索性能相关的重要指标如下：

- query_current：当前正在进行的查询数。集群当前正在处理的查询计数。
- fetch_current：当前正在进行的fetch次数。集群中正在进行的fetch计数。
- query_total：查询总数。集群处理的所有查询的聚合数。
- query_time_in_millis：查询总耗时。所有查询消耗的总时间（以毫秒为单位）。
- fetch_total：提取总数。集群处理的所有fetch的聚合数。
- fetch_time_in_millis：fetch所花费的总时间。所有fetch消耗的总时间（以毫秒为单位）。

## 索引性能维度相关重要指标：

- refresh.total：总刷新计数。刷新总数的计数。
- refresh.total_time_in_millis：刷新总时间。汇总所有花在刷新的时间（以毫秒为单位进行测量）。
- merges.current_docs：目前的合并。合并目前正在处理中。
- merges.total_docs：合并总数。合并总数的计数。
- merges.total_stopped_time_in_millis。合并花费的总时间。合并段的所有时间的聚合。

## 节点运行的重要指标：

- disk.total ：总磁盘容量。节点主机上的总磁盘容量。
- disk.used：总磁盘使用量。节点主机上的磁盘使用总量。
- avail disk：可用磁盘空间总量。
- disk.avail disk.used_percent：使用的磁盘百分比。已使用的磁盘百分比。
- ram：当前的RAM使用情况。当前内存使用量（测量单位）。
- percent ram：RAM百分比。正在使用的内存百分比。
- max : 最大RAM。 节点主机上的内存总量
- cpu：中央处理器。正在使用的CPU百分比。

## JVM运行的重要指标如下：

- mem：内存使用情况。堆和非堆进程和池的使用情况统计信息。
- threads：当前使用的线程和最大数量。
- gc：垃圾收集。算和垃圾收集所花费的总时间。

**Comment by UlricQin** [comment]
已完成集成
