### ISSUE TITLE
mac下./cprobe start失败

### ISSUE THREAD

**Issue by zhangzheming629** [cprobe/cprobe#16]
- 开发环境: mac Big Sur
- 步骤:
   - 执行./cprobe --install显示"service installed"
   - 执行./cprobe --start显示"service started"

但是cprobe并没有成功运行,经过查看代码发现start是执行的`launchctl load /Library/LaunchDaemons/cprobe.plist`
在终端人工执行,发现报错

```
 ./cprobe --install
service installed
 cat /Library/LaunchDaemons/cprobe.plist

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Disabled</key>
	<false/>
	<key>KeepAlive</key>
	<true/>
	<key>Label</key>
	<string>cprobe</string>
	<key>ProgramArguments</key>
	<array>
		<string>/Users/user/code/cprobe/cprobe</string>
	</array>
	<key>RunAtLoad</key>
	<false/>
	<key>SessionCreate</key>
	<false/>
	<key>StandardErrorPath</key>
	<string>/var/log/cprobe.err.log</string>
	<key>StandardOutPath</key>
	<string>/var/log/cprobe.out.log</string>
</dict>
</plist>
 ./cprobe --start
service started

launchctl list cprobe
{
	"StandardOutPath" = "/var/log/cprobe.out.log";
	"LimitLoadToSessionType" = "Aqua";
	"StandardErrorPath" = "/var/log/cprobe.err.log";
	"Label" = "cprobe";
	"OnDemand" = false;
	"LastExitStatus" = 19968;
	"Program" = "/Users/zhangzheming/code/cprobe/cprobe";
	"ProgramArguments" = (
		"/Users/zhangzheming/code/cprobe/cprobe";
	);
};
```

```
launchctl load /Library/LaunchDaemons/cprobe.plist
Load failed: 5: Input/output error
```

**Comment by zhangzheming629** [comment]
卸载并重新加载服务
- launchctl unload /Library/LaunchDaemons/cprobe.plist
- launchctl load /Library/LaunchDaemons/cprobe.plist

 launchctl load不再报错"Load failed: 5: Input/output error", /var/log/cprobe.out.log和/var/log/cprobe.err.log是空的，暂不确定是否正常运行

**Comment by zhangzheming629** [comment]
chmod +x /Library/LaunchDaemons/cprobe.plist

**Comment by UlricQin** [comment]
你自己编译的mac下的二进制？github release页面并未提供二进制

**Comment by zhangzheming629** [comment]
> mac下没测过install和start命令，直接 ./cprobe 运行即可

好的

**Comment by zhangzheming629** [comment]
总结一下 

mac运行cprobe 
  - ./cprobe运行
  - service运行  `暂不可行`
    - ./cprobe --install  
      - 生成service文件/Library/LaunchDaemons/cprobe.plist
      - 需要赋予执行权限 chmod +x /Library/LaunchDaemons/cprobe.plist  
    - launchctl list cprobe  查看service信息
    - ./cprobe --start 运行

       start背后的命令launchctl load /Library/LaunchDaemons/cprobe.plist
    - 日志文件  无输出
      - /var/log/cprobe.err.log
      - /var/log/cprobe.out.log

**Comment by UlricQin** [comment]
<img width="884" alt="image" src="https://github.com/cprobe/cprobe/assets/2769466/6705dfe0-6a36-4954-95f4-11e40150e434">

最新版本我修复了一下，可以再试试

**Comment by zhangzheming629** [comment]
好的
