### ISSUE TITLE
Add a common 'up{}' metric to validate the success of all collected metric data

### ISSUE THREAD

**Issue by Brant-lzh** [cprobe/cprobe#21]
Add a common 'up{}' metric to validate the success of all collected metric data
希望每个target都默认生成一个up{} 指标，用于判断整个采集过程的成功性。

**Comment by UlricQin** [comment]
刚才看一下代码，想加一下这个通用的 up 指标以及 scrape_duration_seconds 指标，这俩指标都是通用的，但是发现，有些插件已经生成了这类指标，而且有固有的命名，如果改掉的话，之前 Prometheus 生态的 Grafana 大盘就没法直接使用了，尴尬

**Comment by Brant-lzh** [comment]
我感觉命名不冲突就行了，例如：cprobe_up{} 、cprobe_scrape_duration_seconds{}，这样只是多了两个指标，Prometheus 生态的 Grafana 大盘还可以直接使用吧

**Comment by UlricQin** [comment]
嗯，弄个新名字确实不影响老大盘，不过总感觉多此一举。还有一个麻烦点是现在很多代码是fork自exporter（比如redis-exporter、mysqld-exporter），很多exporter的代码是异步执行Collect来采集数据，如果要把内部采集数据时遇到的error返回出来，就得破坏Collect方法的签名了，需要让这个方法返回一个error，然后层层传上去，一直传到Scrape方法之外。当然，反正cprobe已经魔改了各个exporter，再多魔改一点也没啥大不了的，哈哈。我再挨个插件看看，想想是否下这个决心。

**Comment by Brant-lzh** [comment]
因为我觉得当采集上百个target时，如果没有一些默认采集指标进行采集状况进行判断，很难直观地快速判断到底是哪个target有没有采集成功，采集失败还是上传失败只能通过log去发现。
当然现在这样下沉到每个类型下实现也是可以的，但感觉有点冗余~

**Comment by UlricQin** [comment]
这个 up 指标肯定是需要的，这个是个一致意见。只是放到哪里实现的问题了。目前的现状是各个插件都单独实现的。我今天看看每个插件的入口函数，再琢磨琢磨

**Comment by Brant-lzh** [comment]
是的，没错

**Comment by UlricQin** [comment]
done
