### ISSUE TITLE
grafana版本支持问题

### ISSUE THREAD

**Issue by einnse** [cprobe/cprobe#34]
提供的redis仪表盘，导入监控展示报错
```
Templating
Failed to upgrade legacy queries e.replace is not a function
```
 使用的版本grafana:7.5.15，是grafana版本太低了吗

**Comment by UlricQin** [comment]
> 提供的redis仪表盘，导入监控展示报错
> 
> ```
> Templating
> Failed to upgrade legacy queries e.replace is not a function
> ```
> 
> 使用的版本grafana:7.5.15，是grafana版本太低了吗

下载新版本测试，这是完全可以自行验证的问题
