### ISSUE TITLE
集成node_exporter

### ISSUE THREAD

**Issue by haigeek** [cprobe/cprobe#43]
请问一下目前暂未接入[node_exporter](https://github.com/prometheus/node_exporter)的原因是？是否有考虑接入

**Comment by UlricQin** [comment]
node_exporter 相对比较特殊，是在所有目标机器上都要部署的组件，要求轻量级、稳定可靠、占用的 CPU、内存少，不太需要经常升级。cprobe 则更像是一个中心探针，采集远端的监控目标，本质上，和 node_exporter 是两个部署模式，所以就没有集成进来。短期也没有计划要集成，主要是没有很强有力的理由支持这么做。

**Comment by haigeek** [comment]
了解了，感谢解答。
